### ISSUE TITLE
Onboard vtuber_name_here

### ISSUE THREAD

**Issue by BurnTheNotice** [clovenski/vtuber-schedules#11]
Fill out the below information to request onboarding a VTuber.

**Name**: Dee_the_Sphinx

**Platform**: twitch

**Affiliation (if any)**: Indie

**Link to channel**: https://www.twitch.tv/dee_the_sphinx

Thank you!

If you're still interested in adding people, I'll recommend a few.

**Comment by clovenski** [comment]
Hello! Thanks for the request.
I added dee to the website. Let me know if you have any questions.

And yeah, feel free to recommend more if you'd like!
Feel free to recommend a list of VTubers all in one request.
