### ISSUE TITLE
Onboard vtuber_name_here

### ISSUE THREAD

**Issue by BurnTheNotice** [clovenski/vtuber-schedules#12]
As per your answer, a small list, then, for a few Tubas. Thank you for your services!

**Name**: Himura Kuraudo
**Platform**: twitch
**Affiliation (if any)**: Mascot VTuber for the HyperX Brand
(So I've seen there's actual people streaming in a promo sort of stream. Once in the last...like, 5 months, I think? It's your discretion, if you want that on your page, of course)
**Link to channel**: https://www.twitch.tv/hyperx

**Name**: ProbablyMeldoy
**Platform**: Youtube
**Affiliation (if any)**: Indie
**Link to channel**: https://www.youtube.com/@ProbMelody

**Name**: nosharko
**Platform**: twitch
**Affiliation (if any)**: Indie
**Link to channel**: https://www.twitch.tv/nosharko

**Name**: grimmiVT
**Platform**: twitch
**Affiliation (if any)**: Indie
**Link to channel**: https://www.twitch.tv/grimmivt

**Name**: FRAIKI
**Platform**: twitch
**Affiliation (if any)**: Indie
**Link to channel**: https://www.twitch.tv/fraiki

**Name**: Orion Twins
**Platform**: Youtube
**Affiliation (if any)**: Indie
**Link to channel**: https://www.youtube.com/@oriontwins

**Name**: Buoy Afuru
**Platform**: Youtube
**Affiliation (if any)**: CiesteVT
**Link to channel**: https://www.youtube.com/@BuoyAfuru

**Name**: Chiyo Moberi
**Platform**: Youtube
**Affiliation (if any)**: CiesteVT
**Link to channel**: https://www.youtube.com/@ChiyoMoberi

**Name**: Mila Marlenka
**Platform**: Youtube
**Affiliation (if any)**: CiesteVT
**Link to channel**: https://www.youtube.com/@MilaMarlenka

**Name**: Capo Miyo
**Platform**: Youtube
**Affiliation (if any)**: Indie
**Link to channel**: https://www.youtube.com/@CapoMiyo/featured

**Name**: Pythea Eriopalid
**Platform**: Youtube
**Affiliation (if any)**: Indie
**Link to channel**: https://www.youtube.com/@PytheaEriopalid/featured

I think that's enough...for now..Thank you, genuinely.

**Comment by clovenski** [comment]
They're all onboarded! Let me know if you see anything wrong.

Hope this website helps you out! Thanks for the requests.
