### ISSUE TITLE
Onboard Denauth Wave

### ISSUE THREAD

**Issue by Jamiie-Jamiie** [clovenski/vtuber-schedules#13]
Fill out the below information to request onboarding a VTuber.

**Name**: Ryoma Barrenwort

**Platform**: Youtube

**Affiliation (if any)**: Nijisanji

**Link to channel**: https://www.youtube.com/@RyomaBarrenwort

_______________________________________________________________________________

**Name**: Klara Charmwood

**Platform**: Youtube

**Affiliation (if any)**: Nijisanji

**Link to channel**: https://www.youtube.com/@KlaraCharmwood

______________________________________________________________________________

**Name**: Twisty Amanozako

**Platform**: Youtube

**Affiliation (if any)**: Nijisanji

**Link to channel**: https://www.youtube.com/@TwistyAmanozako

Thank you!

**Comment by clovenski** [comment]
Thanks for the request! They've all been added.
