### ISSUE TITLE
Onboard Kaminari Clara (Phase Connect)

### ISSUE THREAD

**Issue by zammation** [clovenski/vtuber-schedules#15]
Fill out the below information to request onboarding a VTuber.

**Name**: 
Kaminari Clara
**Platform**: 
YouTube
**Affiliation (if any)**: 
Phase Connect
**Link to channel**: 
https://www.youtube.com/@kaminariclara

Thank you!

**Comment by zammation** [comment]
Technically she's under Phase Connect JP, but she's been doing a lot more English streams

**Comment by clovenski** [comment]
Hello!
Thanks for the request.
Yeah, I added all of the first gen of Phase Connect JP which includes Clara.
