### ISSUE TITLE
Onboard marimari_en (Mythic Talent)

### ISSUE THREAD

**Issue by zammation** [clovenski/vtuber-schedules#16]
Fill out the below information to request onboarding a VTuber.

**Name**: 
marimari_en (yes the underscore is part of her actual name)
**Platform**: 
Twitch
**Affiliation (if any)**: 
Mythic Talent
**Link to channel**: 
https://www.twitch.tv/marimari_en

Thank you!

**Comment by clovenski** [comment]
Thanks for the request!

I added marimari to the website, under the Mythic Talent affiliation.
