### ISSUE TITLE
Onboard Lord Aethelstan

### ISSUE THREAD

**Issue by lifebound** [clovenski/vtuber-schedules#4]
Fill out the below information to request onboarding a VTuber.

**Name**: Lord Aethelstan

**Platform**: Twitch

**Affiliation (if any)**:  MSM

**Link to channel**:  https://www.twitch.tv/lordaethelstan

Thank you!

**Comment by clovenski** [comment]
Hey, thanks for the request!

Lord Aethelstan is now on there. You can reopen this to let me know if it doesn't show up for you.

Otherwise, cheers!
