### ISSUE TITLE
Onboard Rosco Graves

### ISSUE THREAD

**Issue by Jamiie-Jamiie** [clovenski/vtuber-schedules#5]
Fill out the below information to request onboarding a VTuber.

**Name**: Rosco Graves

**Platform**: Youtube

**Affiliation (if any)**: First Stage Production EN

**Link to channel**: https://www.youtube.com/@roscograves

Thank you!

**Comment by clovenski** [comment]
Hello!
I've added them to the website. Let me know if you have any questions.

Thanks!
