### ISSUE TITLE
Onboard Lucien Lunaris

### ISSUE THREAD

**Issue by Jamiie-Jamiie** [clovenski/vtuber-schedules#6]
Fill out the below information to request onboarding a VTuber.

**Name**: Lucien Lunaris

**Platform**: Youtube

**Affiliation (if any)**: First Stage Production EN

**Link to channel**: https://www.youtube.com/@LucienLunaris

Thank you!

**Comment by clovenski** [comment]
Hello!
I've added them to the website. Let me know if you have any questions.

Thanks!
