### ISSUE TITLE
Onboard Cassian Floros

### ISSUE THREAD

**Issue by Jamiie-Jamiie** [clovenski/vtuber-schedules#8]
Fill out the below information to request onboarding a VTuber.

**Name**: Cassian Floros

**Platform**: Youtube

**Affiliation (if any)**: First Stage Production EN

**Link to channel**: https://www.youtube.com/@CassianFloros

Thank you!

**Comment by clovenski** [comment]
Hello!
I've added them to the website. Let me know if you have any questions.

Thanks!
