### ISSUE TITLE
Onboard Zander Netherbrand

### ISSUE THREAD

**Issue by Jamiie-Jamiie** [clovenski/vtuber-schedules#9]
Fill out the below information to request onboarding a VTuber.

**Name**: Zander Netherbrand

**Platform**: Youtube

**Affiliation (if any)**: First Stage Production EN

**Link to channel**: https://www.youtube.com/@ZanderNetherbrand

Thank you!
Sorry about the spam !!

**Comment by clovenski** [comment]
Hello!
I've added them to the website. Let me know if you have any questions.

And no worries about the spam! Happy to onboard your oshis onto this website :D

Thanks!
